"""Generates fpga/nexys_a7.xdc from Digilent's Nexys-A7-100T master XDC,
keeping only the ports the top level uses, with their pins unchanged.

usage: python3 tools/gen_xdc.py <Nexys-A7-100T-Master.xdc> fpga/nexys_a7.xdc
"""
import re
import sys

PORTS = (["CLK100MHZ", "CPU_RESETN", "UART_TXD_IN", "UART_RXD_OUT", "LED16_R"]
         + [f"SW[{i}]" for i in range(16)] + [f"LED[{i}]" for i in range(16)])

master = open(sys.argv[1]).read().splitlines()
out = ["## K-means SoC on the Nexys A7-100T (xc7a100tcsg324-1)",
       "## Generated by tools/gen_xdc.py from Digilent's Nexys-A7-100T-Master.xdc;",
       "## pin locations and I/O standards are unchanged.", ""]
found = set()
for line in master:
    m = re.match(r"^#\s*(set_property .*\[get_ports \{\s*([\w\[\]]+)\s*\}\];?)", line)
    if m and m.group(2) in PORTS:
        out.append(m.group(1).rstrip(";").strip())
        found.add(m.group(2))
    c = re.match(r"^#\s*(create_clock .*CLK100MHZ.*?)\s*;?\s*$", line)
    if c:
        out.append(c.group(1).rstrip(";"))
missing = set(PORTS) - found
if missing:
    sys.exit(f"gen_xdc: not found in the master file: {sorted(missing)}")
out += ["",
        "## The UART and switches are asynchronous inputs, synchronised in the design.",
        "set_false_path -from [get_ports {UART_TXD_IN SW[*] CPU_RESETN}]",
        "",
        "set_property CFGBVS VCCO [current_design]",
        "set_property CONFIG_VOLTAGE 3.3 [current_design]"]
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print(f"{len(found)} ports constrained")
