"""Generates sw/crc16_table.h: the CRC-16/CCITT-FALSE lookup table, as a
constant so it lives in the RAM image instead of being built at start-up."""
import sys

rows = []
for i in range(256):
    c = i << 8
    for _ in range(8):
        c = ((c << 1) ^ 0x1021) if c & 0x8000 else (c << 1)
        c &= 0xFFFF
    rows.append(c)

out = ["// Generated by tools/gen_crc_table.py. Do not edit.",
       "// CRC-16/CCITT-FALSE (poly 0x1021) byte-wise lookup table.",
       "#ifndef CRC16_TABLE_H", "#define CRC16_TABLE_H", "", "#include <stdint.h>", "",
       "static const uint16_t crc_table[256] = {"]
for i in range(0, 256, 8):
    out.append("    " + ", ".join(f"0x{v:04x}" for v in rows[i:i + 8]) + ",")
out += ["};", "", "#endif", ""]
open(sys.argv[1], "w").write("\n".join(out))
